### ISSUE TITLE
Full Stack delevoper Job

### ISSUE THREAD

**Issue by joaonetocastro** [hackerbay/interview#1]
I would like to know if the job position is still open, so i could start coding the rounds

**Comment by nawazdhandala** [comment]
Yes! We're open.

**Comment by joaonetocastro** [comment]
ok, I'll start the development today

**Comment by joaonetocastro** [comment]
Hi, i finished the round 1, the github url to the repo is here: https://github.com/joaonetocastro/hackerbay-interview-round-1
the DockerHub image url is https://hub.docker.com/r/joaonetocastro/round1
